### ISSUE TITLE
Text cutted on right side for unknow reason

### ISSUE THREAD

**Issue by RafaelLinux** [AdisonCavani/distro-grub-themes#80] opened 2022-08-28 12:23 UTC
**Describe the bug**
Grub menu lines appears cutted, despite there is size enough on line

**Expected behavior**
After installing grub new menu in OpenSUSE, text lines in GRUB menu doesn't appears completely, are cutted all equally on the right.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/13048959/187073890-bb2e6dd7-ffa7-4dfc-a6ce-3c3531d31d09.png)

**Desktop (please complete the following information):**
HD monitor
Operating System: openSUSE Tumbleweed 20220719
KDE Plasma Version: 5.25.3
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5
Kernel Version: 5.18.11-1-default (64-bit)
Graphics Platform: X11

**Comment by AdisonCavani** [comment] 2022-08-28 20:36
Hi. This looks like a duplicate of issue #30. 
Let me know, if the issue is resolved. Thanks

**Closed** 2022-08-29 00:46 UTC
Labels: bug, duplicate
